### ISSUE TITLE
index.phpをOOP

### ISSUE THREAD

**Issue by daikisuyama** [daikisuyama/PHP_Sample_Project#16]
表示機能から一覧表示機能と検索機能へと継承

**Comment by daikisuyama-fs** [comment]
Commit id： 81d7fbc84eed905f55773a898091c44548ae0ede
- display.phpにindex.phpをまとめる
  - 抽象化してSQL文をコンストラクタに渡すのみ（継承なし）

**Comment by daikisuyama-fs** [comment]
修正完了
