### ISSUE TITLE
オブジェクト指向に書き直す

### ISSUE THREAD

**Issue by daikisuyama** [daikisuyama/PHP_Sample_Project#2]
- それぞれの機能オブジェクト指向を用いて書き直す
  - 一覧表示機能
  - 新規作成機能
  - 編集機能
  - 削除機能
  - ページング機能
  - 検索機能

- できるだけ簡潔なページを目指す

**Comment by daikisuyama** [comment]
Commit id： dc987b9b98775234a33b7bd11344e1959446ed3f

- ページング機能は完了

**Comment by daikisuyama** [comment]
Commit id： 23905750478b914961030b3199a738b94f71a633

- SQLの処理は完了

**Comment by daikisuyama-fs** [comment]
Commit id： 81d7fbc84eed905f55773a898091c44548ae0ede

- 一覧表示機能と検索機能と編集機能（表示機能）は完了

**Comment by daikisuyama-fs** [comment]
Commit id： df05bf2a2821e4541c48b1512a9ee13cd209d2ce
- 編集機能（更新）と削除機能と作成機能も完了

**Comment by daikisuyama-fs** [comment]
もう少しまとめられるとこをまとめて完成

**Comment by daikisuyama-fs** [comment]
面倒なのでこれ以上はやらない
