### ISSUE TITLE
並び替え機能を作る

### ISSUE THREAD

**Issue by daikisuyama** [daikisuyama/PHP_Sample_Project#3]
タイトルの通り

**Comment by daikisuyama-fs** [comment]
Commit id： 98cba7a56aef0ce1780749a9289bb9119709c089

- JSのバグとり
  - 他のファイルの埋め込み方
  - search_dialog関数の修正
- 並び替え機能の作成
  - セレクトボックスのJSによる実装

**Comment by daikisuyama-fs** [comment]
作成完了
