### ISSUE TITLE
完了ページがダサい

### ISSUE THREAD

**Issue by daikisuyama** [daikisuyama/PHP_Sample_Project#8]
- 適切なページにリダイレクト
- ダイアログ表示

**Comment by daikisuyama** [comment]
Ajaxを使おうと思っていたんだった

**Comment by daikisuyama-fs** [comment]
alert、dismissingを使いたい

**Comment by daikisuyama-fs** [comment]
4/24中に対応予定

**Comment by daikisuyama-fs** [comment]
最優先でやる

**Comment by daikisuyama-fs** [comment]
Commit id： 404c8774282f06601fdfc6eec88f7ccefe03f573
- alert出力用のdivをindex.phpに作成
- Ajaxを作成機能に適用

**Comment by daikisuyama-fs** [comment]
Commit id： 553c565013d6b8304e79d4c1125c890c6a31cecf
- Ajaxを更新機能に適用

**Comment by daikisuyama-fs** [comment]
Commit id： a435bea66b6989fe06d5ed1ccb2d01a84e73f44a
- Ajaxを削除機能に適用

**Comment by daikisuyama-fs** [comment]
Commit id：33e017035e985466abcb6d6a9f64a0288cf8a2d2
- Ajaxのコードを更新

**Comment by daikisuyama-fs** [comment]
修正完了
